import type { MuscleGroup } from '../types';

export interface ExerciseCatalogItem {
  id: string;
  name: string;
  nameTh: string;
  muscle: MuscleGroup;
  muscleLabelTh: string;
  muscleLabelEn: string;
  targetMuscleTh: string;
  targetMuscleEn: string;
  tipsTh: string;
  tipsEn: string;
  baseWeightKg: number;
  defaultReps: string;
  isPopular?: boolean;
}

export const EXERCISE_CATALOG: ExerciseCatalogItem[] = [
  // --- CHEST ---
  {
    id: 'chest_press_machine',
    name: 'Chest Press Machine',
    nameTh: 'เครื่องดันอกท่านั่ง (Chest Press)',
    muscle: 'chest',
    muscleLabelTh: 'อก',
    muscleLabelEn: 'Chest',
    targetMuscleTh: 'อกส่วนกลาง & หลังแขน',
    targetMuscleEn: 'Mid Chest & Triceps',
    tipsTh: 'นั่งหลังแนบเบาะ ปรับด้ามจับเสมอราวนม ดันไปข้างหน้าพร้อมหายใจออก เกร็งอกค้าง 1 วิ ไม่ล็อกศอก ช่วยสร้างความหนาและทรงอกที่ได้รูป',
    tipsEn: 'Sit firmly against backrest. Align handles with mid-chest. Press forward while exhaling and squeezing chest without locking elbows.',
    baseWeightKg: 40,
    defaultReps: '15 ที',
    isPopular: true,
  },
  {
    id: 'pec_deck_machine',
    name: 'Pec Deck Machine (อก)',
    nameTh: 'เครื่องบีบชิดร่องอก (Pec Deck Fly)',
    muscle: 'chest',
    muscleLabelTh: 'อก',
    muscleLabelEn: 'Chest',
    targetMuscleTh: 'ร่องอกใน & ขอบอกล่าง',
    targetMuscleEn: 'Inner Chest & Sternal Pecs',
    tipsTh: 'ปรับเบาะให้ข้อศอกขนานระนาบราวนม กางแขนรับแรงต้าน แล้วบีบแขนเข้าหากันด้านหน้า ค้าง 1 วิ เพื่อให้ร่องอกชัดและอกกระชับทรงสวย',
    tipsEn: 'Adjust seat so elbows are parallel to chest. Fly arms inward until handles touch, hold for 1 sec to isolate inner chest cleavage.',
    baseWeightKg: 35,
    defaultReps: '15 ที',
    isPopular: true,
  },
  {
    id: 'incline_dumbbell_press',
    name: 'Incline Dumbbell Press',
    nameTh: 'ดัมเบลล์ดันอกบน (Incline Press)',
    muscle: 'chest',
    muscleLabelTh: 'อก',
    muscleLabelEn: 'Chest',
    targetMuscleTh: 'อกส่วนบน & ไหล่หน้า',
    targetMuscleEn: 'Upper Chest & Front Delts',
    tipsTh: 'ปรับเบาะเอียง 30-45 องศา ดันดัมเบลล์ขึ้นเป็นแนวโค้งเข้าหากันเหนือยอดอก ควบคุมจังหวะลงช้าๆ ช่วยให้อกส่วนบนเต็มแน่น ดูผึ่งผาย',
    tipsEn: 'Set incline bench to 30-45°. Press dumbbells upward in a slight arc, focusing on upper pectoral contraction.',
    baseWeightKg: 20,
    defaultReps: '15 ที',
    isPopular: true,
  },
  {
    id: 'cable_chest_flyes',
    name: 'Cable Chest Flyes',
    nameTh: 'เคเบิลครอสโอเวอร์อก (Cable Flyes)',
    muscle: 'chest',
    muscleLabelTh: 'อก',
    muscleLabelEn: 'Chest',
    targetMuscleTh: 'กล้ามเนื้ออกรอบทิศ & อกล่าง',
    targetMuscleEn: 'Lower & Outer Chest Squeeze',
    tipsTh: 'ยืนก้าวขาข้างหนึ่ง โน้มตัวเล็กน้อย ดึงสายเคเบิลจากมุมบนลงมาประกบกันข้างหน้าล่าง โฟกัสการบีบกล้ามเนื้ออกตลอดการเคลื่อนไหว',
    tipsEn: 'Step forward slightly, lean with a flat back. Pull cables inward and downward together, maintaining continuous muscle tension.',
    baseWeightKg: 15,
    defaultReps: '15 ที',
    isPopular: true,
  },
  {
    id: 'barbell_bench_press',
    name: 'Barbell Bench Press',
    nameTh: 'บาร์เบลล์ดันอกท่านอน (Bench Press)',
    muscle: 'chest',
    muscleLabelTh: 'อก',
    muscleLabelEn: 'Chest',
    targetMuscleTh: 'อกรวม & พละกำลังดันตัว',
    targetMuscleEn: 'Overall Chest & Pushing Power',
    tipsTh: 'นอนราบ แขนกว้างกว่าไหล่เล็กน้อย ปลดบาร์ลงมาแตะกลางอก แล้วออกแรงดันขึ้นตรงๆ สร้างแรงผลักและมวลกล้ามเนื้ออกหลัก',
    tipsEn: 'Lie flat, grip slightly wider than shoulders. Lower bar to mid-chest, then press forcefully upward.',
    baseWeightKg: 50,
    defaultReps: '15 ที',
    isPopular: false,
  },

  // --- BACK ---
  {
    id: 'lat_pulldown_machine',
    name: 'Lat Pulldown Machine',
    nameTh: 'เครื่องดึงปีกหลัง (Lat Pulldown)',
    muscle: 'back',
    muscleLabelTh: 'หลัง',
    muscleLabelEn: 'Back',
    targetMuscleTh: 'ปีกหลัง & หลังส่วนบน (V-Shape)',
    targetMuscleEn: 'Latissimus Dorsi & Upper Back',
    tipsTh: 'นั่งล็อกต้นขาใต้เบาะ จับบาร์กว้าง เอนตัวเล็กน้อย ดึงบาร์ลงมาแตะยอดอกพร้อมบีบสะบักเข้าหากัน ช่วยให้แผ่นหลังกว้างเป็นรูป V-Taper',
    tipsEn: 'Lock thighs under pads. Wide grip on bar, pull down to upper chest while arching slightly and squeezing shoulder blades.',
    baseWeightKg: 45,
    defaultReps: '15 ที',
    isPopular: true,
  },
  {
    id: 'seated_cable_row',
    name: 'Seated Cable Row (หลัง)',
    nameTh: 'เคเบิลดึงหลังท่านั่ง (Cable Row)',
    muscle: 'back',
    muscleLabelTh: 'หลัง',
    muscleLabelEn: 'Back',
    targetMuscleTh: 'กลางหลัง & สะบัก (แก้ไหล่ห่อ)',
    targetMuscleEn: 'Mid Back, Rhomboids & Posture',
    tipsTh: 'นั่งหลังตรง ยืดอก ดึงด้ามจับเข้าหาหน้าท้องส่วนล่าง บีบสะบักค้าง 1 วิ ห้ามเหวี่ยงตัว ช่วยเพิ่มความหนาของแผ่นหลังและแก้อาการไหล่ห่อ',
    tipsEn: 'Sit upright, chest out. Pull handle towards lower abdomen, squeezing shoulder blades together without swinging torso.',
    baseWeightKg: 40,
    defaultReps: '15 ที',
    isPopular: true,
  },
  {
    id: 'barbell_bent_over_row',
    name: 'Barbell Bent-over Row',
    nameTh: 'บาร์เบลล์ก้มตัวดึงหลัง (Bent-over Row)',
    muscle: 'back',
    muscleLabelTh: 'หลัง',
    muscleLabelEn: 'Back',
    targetMuscleTh: 'หลังส่วนกลาง & หลังล่าง',
    targetMuscleEn: 'Mid Back & Core Stabilizers',
    tipsTh: 'พับสะโพก หลังตรงขนานพื้น 45 องศา ดึงบาร์ขึ้นเข้าหาใต้สะดือ บีบกล้ามเนื้อหลังให้สุด สร้างความหนาและทรงหลังที่แข็งแกร่ง',
    tipsEn: 'Hinge at hips with flat back at 45°. Pull barbell to navel, driving elbows back to maximize back thickness.',
    baseWeightKg: 40,
    defaultReps: '15 ที',
    isPopular: false,
  },
  {
    id: 'face_pulls',
    name: 'Face Pulls',
    nameTh: 'เคเบิลดึงเข้าใบหน้า (Face Pulls)',
    muscle: 'back',
    muscleLabelTh: 'หลัง',
    muscleLabelEn: 'Back',
    targetMuscleTh: 'สะบักบน & ไหล่หลัง (แก้คอยื่น)',
    targetMuscleEn: 'Rear Delts & Upper Trapezius',
    tipsTh: 'ตั้งเคเบิลระดับสายตา จับเชือกดึงเข้าหาใบหน้า กางศอกสูงและหมุนแขนออกด้านนอก ช่วยปรับบุคลิกภาพ แก้อาการไหล่ห่อคอยื่น',
    tipsEn: 'Set cable at eye level. Pull rope towards face while flaring elbows high and rotating outwards. Great for posture.',
    baseWeightKg: 17.5,
    defaultReps: '15 ที',
    isPopular: false,
  },

  // --- LEGS ---
  {
    id: 'leg_press_45',
    name: 'Leg Press 45°',
    nameTh: 'เครื่องถีบขามุม 45 องศา (Leg Press)',
    muscle: 'legs',
    muscleLabelTh: 'ขา',
    muscleLabelEn: 'Legs',
    targetMuscleTh: 'ต้นขาหน้า & กล้ามเนื้อก้นสะโพก',
    targetMuscleEn: 'Quadriceps & Gluteus Maximus',
    tipsTh: 'วางเท้ากลางแป้นกว้างเท่าไหล่ ปลดล็อกแล้วหย่อนขาลงมามุมฉาก ออกแรงถีบขึ้นโดยไม่ล็อกเข่า สร้างขาแน่นแข็งแรงโดยไม่กดหลัง',
    tipsEn: 'Place feet shoulder-width on platform. Lower sled to 90°, press through heels without locking knees to protect joints.',
    baseWeightKg: 80,
    defaultReps: '15 ที',
    isPopular: true,
  },
  {
    id: 'leg_extension',
    name: 'Leg Extension (ขาหน้า)',
    nameTh: 'เครื่องเตะขาหน้า (Leg Extension)',
    muscle: 'legs',
    muscleLabelTh: 'ขา',
    muscleLabelEn: 'Legs',
    targetMuscleTh: 'กล้ามเนื้อต้นขาด้านหน้า (หน้าขาคม)',
    targetMuscleEn: 'Quadriceps Peak Isolation',
    tipsTh: 'นั่งพิงเบาะ ล็อกข้อเท้าไว้ใต้ฟองน้ำ เตะขาขึ้นให้เหยียดตรง เกร็งหน้าขาค้างไว้ 1 วิ แล้วค่อยๆ ผ่อนลง ช่วยตัดขอบหน้าขาให้คมชัด',
    tipsEn: 'Sit with back supported. Place ankles under pad and extend legs until straight. Hold for 1 sec to isolate quadriceps.',
    baseWeightKg: 35,
    defaultReps: '15 ที',
    isPopular: true,
  },
  {
    id: 'lying_leg_curl',
    name: 'Lying Leg Curl (ขาหลัง)',
    nameTh: 'เครื่องงอขาหลังท่านอน (Leg Curl)',
    muscle: 'legs',
    muscleLabelTh: 'ขา',
    muscleLabelEn: 'Legs',
    targetMuscleTh: 'กล้ามเนื้อต้นขาด้านหลัง (Hamstrings)',
    targetMuscleEn: 'Hamstrings & Knee Stabilizers',
    tipsTh: 'นอนคว่ำ ล็อกข้อเท้าใต้เบาะ งอขาพับขึ้นหาก้น เกร็งต้นขาหลังแล้วค่อยๆ คลายลง ช่วยป้องกันการบาดเจ็บของเข่าและสร้างสมดุลขา',
    tipsEn: 'Lie facedown with ankles under pad. Curl legs upward towards glutes, controlling descent to build hamstring strength.',
    baseWeightKg: 30,
    defaultReps: '15 ที',
    isPopular: true,
  },
  {
    id: 'standing_calf_raise',
    name: 'Standing Calf Raise',
    nameTh: 'เครื่องเขย่งน่องท่ายืน (Calf Raise)',
    muscle: 'legs',
    muscleLabelTh: 'ขา',
    muscleLabelEn: 'Legs',
    targetMuscleTh: 'กล้ามเนื้อน่อง (เรียวเฟิร์ม)',
    targetMuscleEn: 'Calves (Gastrocnemius)',
    tipsTh: 'ยืนปลายเท้าวางบนแท่น ทิ้งส้นเท้าลงเพื่อยืดน่อง แล้วออกแรงเขย่งปลายเท้าขึ้นสูงสุด เกร็งน่อง 1 วิ ช่วยให้น่องเฟิร์มกระชับได้สัดส่วน',
    tipsEn: 'Stand on edge of step. Lower heels for a deep stretch, then rise onto tiptoes, pausing at peak contraction for defined calves.',
    baseWeightKg: 40,
    defaultReps: '15 ที',
    isPopular: false,
  },

  // --- SHOULDERS ---
  {
    id: 'shoulder_press_machine',
    name: 'Shoulder Press Machine',
    nameTh: 'เครื่องดันไหล่ท่านั่ง (Shoulder Press)',
    muscle: 'shoulders',
    muscleLabelTh: 'ไหล่',
    muscleLabelEn: 'Shoulders',
    targetMuscleTh: 'หัวไหล่รวม (หน้าและข้าง)',
    targetMuscleEn: 'Front & Lateral Deltoids',
    tipsTh: 'นั่งหลังพิงเบาะให้ตรง จับด้ามจับ ดันขึ้นเหนือศีรษะจนแขนเกือบตึง ไม่แอ่นหลัง ช่วยสร้างหัวไหล่ให้ดูกว้างและบึกบึน',
    tipsEn: 'Sit upright against pad. Press handles directly overhead until arms are nearly straight, avoiding lower back arching.',
    baseWeightKg: 30,
    defaultReps: '15 ที',
    isPopular: true,
  },
  {
    id: 'dumbbell_lateral_raise',
    name: 'Dumbbell Lateral Raise',
    nameTh: 'ดัมเบลล์กางแขนยกไหล่ข้าง (Lateral Raise)',
    muscle: 'shoulders',
    muscleLabelTh: 'ไหล่',
    muscleLabelEn: 'Shoulders',
    targetMuscleTh: 'หัวไหล่ข้าง (สร้างไหล่กว้าง 3D)',
    targetMuscleEn: 'Side Delts (Shoulder Width)',
    tipsTh: 'ยืนทรงตัว กางแขนยกดัมเบลล์ออกข้างลำตัวเสมอระดับไหล่ งอศอกเล็กน้อยเหมือนเทน้ำ ช่วยให้หัวไหล่ดูกลมกว้างเป็นทรงลูกมะพร้าว',
    tipsEn: 'Stand upright, lift dumbbells outward to shoulder height with a slight elbow bend. Builds 3D rounded cannonball shoulders.',
    baseWeightKg: 8,
    defaultReps: '15 ที',
    isPopular: true,
  },
  {
    id: 'reverse_pec_deck_fly',
    name: 'Reverse Pec Deck Fly',
    nameTh: 'เครื่องกางแขนไหล่หลัง (Reverse Fly)',
    muscle: 'shoulders',
    muscleLabelTh: 'ไหล่',
    muscleLabelEn: 'Shoulders',
    targetMuscleTh: 'หัวไหล่ด้านหลัง (Rear Delts)',
    targetMuscleEn: 'Rear Deltoids & Upper Posture',
    tipsTh: 'นั่งหันหน้าเข้าหาเบาะ กางแขนดึงมือจับไปข้างหลังในระนาบขนานพื้น บีบกล้ามเนื้อไหล่หลัง ช่วยให้หัวไหล่กลมกลืนรอบด้าน',
    tipsEn: 'Sit chest against pad. Grip handles and pull arms backward horizontally, targeting rear delts to balance shoulder posture.',
    baseWeightKg: 25,
    defaultReps: '15 ที',
    isPopular: false,
  },

  // --- ARMS ---
  {
    id: 'preacher_curl_machine',
    name: 'Preacher Curl Machine (หน้าแขน)',
    nameTh: 'เครื่องล็อกศอกดึงหน้าแขน (Preacher Curl)',
    muscle: 'arms',
    muscleLabelTh: 'แขน',
    muscleLabelEn: 'Arms',
    targetMuscleTh: 'ลูกหนูหน้าแขน (Biceps Peak)',
    targetMuscleEn: 'Biceps Brachii Peak',
    tipsTh: 'วางต้นแขนแนบเบาะเอียง ล็อกศอกให้อยู่กับที่ ออกแรงดึงมือจับขึ้น เกร็งบีบหน้าแขนสุด แล้วผ่อนลงช้าๆ ช่วยสร้างลูกหนูหน้าแขนให้คมนูน',
    tipsEn: 'Rest upper arms on preacher pad. Curl handles upward, squeezing biceps at peak without shifting elbows.',
    baseWeightKg: 25,
    defaultReps: '15 ที',
    isPopular: true,
  },
  {
    id: 'tricep_rope_pushdown',
    name: 'Tricep Rope Pushdown (หลังแขน)',
    nameTh: 'เคเบิลเชือกกดหลังแขน (Tricep Pushdown)',
    muscle: 'arms',
    muscleLabelTh: 'แขน',
    muscleLabelEn: 'Arms',
    targetMuscleTh: 'หลังแขนรูปเกือกม้า (Triceps)',
    targetMuscleEn: 'Triceps Lateral & Long Head',
    tipsTh: 'ยืนโน้มตัวเล็กน้อย ล็อกข้อศอกแนบข้างลำตัว กดเชือกลงมาตรงๆ แล้วกางปลายเชือกออกข้างสะโพก ช่วยให้แขนกระชับ เฟิร์มแน่นไม่ย้วย',
    tipsEn: 'Lean slightly forward with elbows pinned to ribs. Push rope downward and flare ends apart at full extension.',
    baseWeightKg: 22.5,
    defaultReps: '15 ที',
    isPopular: true,
  },
  {
    id: 'dumbbell_hammer_curl',
    name: 'Dumbbell Hammer Curl',
    nameTh: 'ดัมเบลล์งอแขนท่าค้อน (Hammer Curl)',
    muscle: 'arms',
    muscleLabelTh: 'แขน',
    muscleLabelEn: 'Arms',
    targetMuscleTh: 'ลำแขนหนา & กล้ามเนื้อท่อนแขน',
    targetMuscleEn: 'Brachialis & Forearm Thickness',
    tipsTh: 'ยืนถือดัมเบลล์หันฝ่ามือเข้าหากัน งอศอกยกดัมเบลล์ขึ้นตรงๆ เหมือนค้อนทุบ ช่วยเพิ่มความหนาของลำแขนและแรงบีบมือ',
    tipsEn: 'Hold dumbbells with neutral palms-in grip. Curl upward like a hammer, building forearm strength and arm thickness.',
    baseWeightKg: 12,
    defaultReps: '15 ที',
    isPopular: false,
  },

  // --- ABS ---
  {
    id: 'cable_crunch_machine',
    name: 'Cable Crunch Machine (หน้าท้อง)',
    nameTh: 'เคเบิลม้วนตัวกล้ามท้อง (Cable Crunch)',
    muscle: 'abs',
    muscleLabelTh: 'หน้าท้อง',
    muscleLabelEn: 'Abs',
    targetMuscleTh: 'ซิกแพคหน้าท้องส่วนบน & กลาง',
    targetMuscleEn: 'Upper & Mid Rectus Abdominis',
    tipsTh: 'คุกเข่า จับเชือกข้างใบหู ม้วนตัวและก้มศีรษะลงหาหัวเข่า บีบกล้ามเนื้อหน้าท้อง ไม่ใช้แรงแขนดึง ช่วยสร้างลอนซิกแพคชัดเจน',
    tipsEn: 'Kneel below high pulley. Hold rope by ears, crunch torso downward towards hips using abdominal compression, not arm pull.',
    baseWeightKg: 30,
    defaultReps: '15 ที',
    isPopular: true,
  },
  {
    id: 'abdominal_crunch_machine',
    name: 'Abdominal Crunch Machine',
    nameTh: 'เครื่องกดซิทอัพหน้าท้อง (Ab Crunch)',
    muscle: 'abs',
    muscleLabelTh: 'หน้าท้อง',
    muscleLabelEn: 'Abs',
    targetMuscleTh: 'กล้ามท้องรวม & กระชับเอว',
    targetMuscleEn: 'Total Core & Waistline',
    tipsTh: 'นั่งพิงเบาะ ล็อกข้อเท้า จับด้ามจับ ออกแรงม้วนตัวและดันตัวไปข้างหน้า บีบกล้ามท้องให้แน่น ช่วยเผาผลาญไขมันหน้าท้องและกระชับเอว',
    tipsEn: 'Sit seated, hold handles. Flex spine forward, contracting abs against resistance to tone core and waistline.',
    baseWeightKg: 35,
    defaultReps: '15 ที',
    isPopular: false,
  },
  {
    id: 'hanging_leg_raise',
    name: 'Hanging Leg Raise',
    nameTh: 'โหนบาร์ยกขาหน้าท้องล่าง (Leg Raise)',
    muscle: 'abs',
    muscleLabelTh: 'หน้าท้อง',
    muscleLabelEn: 'Abs',
    targetMuscleTh: 'กล้ามเนื้อหน้าท้องส่วนล่าง (V-Line)',
    targetMuscleEn: 'Lower Abs & Hip Flexors',
    tipsTh: 'โหนบาร์หรือพิงเครื่องดิป ยกขาขึ้นมาทำมุม 90 องศา ม้วนสะโพกขึ้นเล็กน้อย ช่วยกระชับหน้าท้องส่วนล่างที่สะสมไขมันง่าย',
    tipsEn: 'Hang from bar or dip station. Raise legs up to hip level, curling pelvis slightly forward to ignite lower abs.',
    baseWeightKg: 0,
    defaultReps: '15 ที',
    isPopular: false,
  },
];

/**
 * Fast lookup helper by exact name or partial name match
 */
export function findExerciseDetail(name: string): ExerciseCatalogItem | undefined {
  if (!name) return undefined;
  const cleanName = name.toLowerCase().trim();
  
  // 1. Exact match
  const exact = EXERCISE_CATALOG.find(
    (e) => e.name.toLowerCase() === cleanName || e.nameTh.toLowerCase() === cleanName
  );
  if (exact) return exact;

  // 2. Partial match
  return EXERCISE_CATALOG.find(
    (e) => cleanName.includes(e.name.toLowerCase()) || e.name.toLowerCase().includes(cleanName)
  );
}
